apiVersion: batch/v1
kind: Job
metadata:
  name: certs-backup
  namespace: kube-system
spec:
  template:
    spec:
      restartPolicy: OnFailure
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: "k8s-master1"
      tolerations:
            - key: "node-role.kubernetes.io/control-plane"
              operator: "Exists"
              effect: "NoSchedule"
            - key: "node-role.kubernetes.io/master"   # legacy taint on some clusters
              operator: "Exists"
              effect: "NoSchedule"    
      volumes:
        - name: etcd-backup
          persistentVolumeClaim:
            claimName: etcd-backup-pvc
        - name: pki
          hostPath:
            path: /root/pki
            type: Directory
        - name: kubeconf
          hostPath:
            path: /etc/kubernetes
            type: Directory
      containers:
        - name: copy-certs
          image: busybox:1.36
          command: ["sh", "-c"]
          args:
            - |
              mkdir -p /backup/pki && \
              cp -r /pki/* /backup/pki/ && \
              cp -r /kubeconf/*.conf /backup/pki/ && \
              echo ">>> Certificates copied to PVC"
          volumeMounts:
            - name: etcd-backup
              mountPath: /backup
            - name: pki
              mountPath: /pki
              readOnly: true
            - name: kubeconf
              mountPath: /kubeconf
              readOnly: true

