apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etcd-backup-pvc
  namespace: kube-system
spec:
  storageClassName: nfs-client 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

